### ISSUE TITLE
HsOpenSSL 0.11.1 build fails on Travis CI

### ISSUE THREAD

**Issue by solatis** [phonohawk/HsOpenSSL#37]
Hello,

I am using Travis CI for continuous integration testing of my package, and since the upgrade to version 0.11.1 cabal is unable to compile HsOpenSSL:

> Building HsOpenSSL-0.11.1...
> Preprocessing library HsOpenSSL-0.11.1...
> Option.hsc: In function ‘main’:
> Option.hsc:144:5: error: ‘SSL_OP_SAFARI_ECDHE_ECDSA_BUG’ undeclared (first use in this function)
> Option.hsc:144:5: note: each undeclared identifier is reported only once for each function it appears in compiling dist/build/OpenSSL/SSL/Option_hsc_make.c failed (exit code 1)

https://travis-ci.org/solatis/dissent/builds/45645870

I assume this is caused by some version mismatch between libopenssl installed on the build machine and what HsOpenSSL assumes. Who's at fault here ?

**Comment by phonohawk** [comment]
Thank you for your report. I didn't know `SSL_OP_SAFARI_ECDHE_ECDSA_BUG` was added to OpenSSL that recently. I hope [HsOpenSSL-0.11.1.1](http://hackage.haskell.org/package/HsOpenSSL-0.11.1.1) works for you.

**Comment by solatis** [comment]
Confirmed the fix, thanks!
